// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjfJPGdcrT8NS_rTQFycQD3l9rt6FU_2s',
    appId: '1:1014110738387:web:d5ba3f9842b6a362efc126',
    messagingSenderId: '1014110738387',
    projectId: 'join-1d4a2',
    authDomain: 'join-1d4a2.firebaseapp.com',
    storageBucket: 'join-1d4a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPGKWkyrYEofX5i1DHQpFMxW2ir8_Gnaw',
    appId: '1:1014110738387:android:d7bbf0814489ce67efc126',
    messagingSenderId: '1014110738387',
    projectId: 'join-1d4a2',
    storageBucket: 'join-1d4a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBltdyCUt5paGsQubpUJBRCS_1nxpT7csQ',
    appId: '1:1014110738387:ios:cb0a2068071faa2defc126',
    messagingSenderId: '1014110738387',
    projectId: 'join-1d4a2',
    storageBucket: 'join-1d4a2.firebasestorage.app',
    iosClientId: '1014110738387-4gtccge1sh5qc14cgu8cevc9a74b6e4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.secapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBltdyCUt5paGsQubpUJBRCS_1nxpT7csQ',
    appId: '1:1014110738387:ios:cb0a2068071faa2defc126',
    messagingSenderId: '1014110738387',
    projectId: 'join-1d4a2',
    storageBucket: 'join-1d4a2.firebasestorage.app',
    iosClientId: '1014110738387-4gtccge1sh5qc14cgu8cevc9a74b6e4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.secapps',
  );

}